substitutions:
  # PINS
  pin_i2c_scl: GPIO8
  pin_i2c_sda: GPIO7
  pin_can_tx_pin: GPIO32
  pin_can_rx_pin: GPIO33
  pin_pwm1: GPIO1
  pin_pwm2: GPIO2
  pin_pwm3: GPIO3
  pin_pwm4: GPIO4
  pin_led_h1: GPIO5
  pin_led_h2: GPIO20
  pin_led_v1: GPIO47
  pin_led_v2: GPIO46
  pin_1w: GPIO45
  
  fan_kompressor_min_perc: 20
  fan_kompressor_max_perc: 90
  

